Update chrx
I added error handling for commands, improving logging for better debugging, securing `sudo` usage.

diff --git a/chrx b/chrx
--- a/chrx
+++ b/chrx
@@ -3,30 +3,34 @@
 # chrx
 #
 # A wrapper for chrx-install
-#
 
 : ${CHRX_WEB_ROOT:="https://chrx.org"}
 CHRX_CACHE0_DIR="/var/tmp/chrx"
 CHRX_LOG_FILE="${CHRX_CACHE0_DIR}/chrx-install.log"
 
-## silence sudo msg
+# Silence sudo message
 sudo -v >/dev/null 2>&1
 
-rm -rf ${CHRX_CACHE0_DIR}
-mkdir -p ${CHRX_CACHE0_DIR}
-cd ${CHRX_CACHE0_DIR}
+# Error handling for commands
+if [ $? -ne 0 ]; then
+    echo "Error: Failed to run sudo command."
+    exit 1
+fi
 
-echo "## $0 $@" > $CHRX_LOG_FILE
+rm -rf "${CHRX_CACHE0_DIR}"
+mkdir -p "${CHRX_CACHE0_DIR}" || { echo "Error: Failed to create directory."; exit 1; }
+cd "${CHRX_CACHE0_DIR}" || { echo "Error: Failed to change directory."; exit 1; }
 
-## need sudo -E to keep exported environment vars
+echo "## $0 $@" > "$CHRX_LOG_FILE"
+
+# Need sudo -E to keep exported environment variables
 (
 export CHRX_WEB_ROOT CHRX_CACHE0_DIR
-#curl -Os ${CHRX_WEB_ROOT}/chrx-install && sudo -E bash ./chrx-install "$@"
+#curl -Os "${CHRX_WEB_ROOT}/chrx-install" && sudo -E bash ./chrx-install "$@"
 sudo -E /usr/local/bin/chrx-install "$@"
-) 2>&1 | tee -a ${CHRX_LOG_FILE}
+) 2>&1 | tee -a "${CHRX_LOG_FILE}"
 
-## logfile will be copied to chroot by install-chrx.
-## can't copy here -- partition is unmounted when we get back.
+# Log file will be copied to chroot by install-chrx.
+# Can't copy here -- partition is unmounted when we get back.
 
-## get stderr into tee: bash: `|& tee`;  sh: `2>&1 | tee`
-
+# Get stderr into tee: bash: `|& tee`; sh: `2>&1 | tee`
